name: fst
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  equatable: ^2.0.5
  logger: ^2.0.2+1
  get_it: ^7.6.4
  http: ^1.1.0
  intl_utils: ^2.8.5
  flutter_async_autocomplete: ^0.1.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_gen_runner: any
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images
flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true
flutter_intl:
  enabled: true